"""empty message

Revision ID: 4f9611ee0f98
Revises: fe7d355c9c4f
Create Date: 2019-08-08 20:10:17.581485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9611ee0f98'
down_revision = 'fe7d355c9c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_board', sa.String(length=300), nullable=True),
    sa.Column('destination_board', sa.String(length=300), nullable=True),
    sa.Column('pins_copied', sa.Integer(), server_default='0', nullable=True),
    sa.Column('cursor', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pin_data_destination_board'), 'pin_data', ['destination_board'], unique=False)
    op.create_index(op.f('ix_pin_data_source_board'), 'pin_data', ['source_board'], unique=False)
    op.create_index(op.f('ix_pin_data_user_id'), 'pin_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pin_data_user_id'), table_name='pin_data')
    op.drop_index(op.f('ix_pin_data_source_board'), table_name='pin_data')
    op.drop_index(op.f('ix_pin_data_destination_board'), table_name='pin_data')
    op.drop_table('pin_data')
    # ### end Alembic commands ###
