"""Add stripe session id to payments model

Revision ID: 51f2c1250a6c
Revises: ddd666113fee
Create Date: 2021-05-14 23:42:08.891287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f2c1250a6c'
down_revision = 'ddd666113fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_session_id', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'stripe_session_id')
    # ### end Alembic commands ###
