"""empty message

Revision ID: 56cc9820012c
Revises: ba1c97490b67
Create Date: 2021-05-09 15:13:17.099038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cc9820012c'
down_revision = 'ba1c97490b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pin_data', 'cursor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pin_data', sa.Column('cursor', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
