"""Add pinterest_requests_left in Stats

Revision ID: 667ca5b4803b
Revises: 51e8a819ee05
Create Date: 2021-05-13 15:40:59.041213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667ca5b4803b'
down_revision = '51e8a819ee05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('pinterest_requests_left', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'pinterest_requests_left')
    # ### end Alembic commands ###
