"""Rename total_pins to pins_added in Stats

Revision ID: 935fc790413c
Revises: 747f26af1c9f
Create Date: 2021-05-13 14:26:45.313079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935fc790413c'
down_revision = '747f26af1c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'total_pins', new_column_name='pins_added')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'pins_added', new_column_name='total_pins')
    # ### end Alembic commands ###
