"""Rename first_name to full_name

Revision ID: ba1c97490b67
Revises: af10e48fdb95
Create Date: 2021-04-25 11:52:57.484665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1c97490b67'
down_revision = 'af10e48fdb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pinterest_data', 'first_name', nullable=False, new_column_name='full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pinterest_data', 'full_name', nullable=False, new_column_name='first_name')
    # ### end Alembic commands ###
