"""Change length of source_board in db

Revision ID: ddd666113fee
Revises: 667ca5b4803b
Create Date: 2021-05-14 13:25:05.761662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd666113fee'
down_revision = '667ca5b4803b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pin_data', 'source_board',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pin_data', 'source_board',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###
