"""empty message

Revision ID: e697bedb42e1
Revises: 4f9611ee0f98
Create Date: 2019-08-08 21:13:53.431163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e697bedb42e1'
down_revision = '4f9611ee0f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinterest_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pinterest_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=300), nullable=True),
    sa.Column('first_name', sa.String(length=300), nullable=True),
    sa.Column('last_name', sa.String(length=300), nullable=True),
    sa.Column('pins', sa.Integer(), nullable=True),
    sa.Column('boards', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pinterest_data_user_id'), 'pinterest_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pinterest_data_user_id'), table_name='pinterest_data')
    op.drop_table('pinterest_data')
    # ### end Alembic commands ###
